In [2]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [14]:
data={
    'name':['ravi','pranav','aman'],
    'age':[2,4,5]}
dataset=pd.DataFrame(data)

In [3]:
dataset

NameError: name 'dataset' is not defined

In [4]:
datasets=pd.read_csv(r"C:\Users\sangharatna_2022\OneDrive\Desktop\Python\Python-Libraries\index_1.csv")
datasets.head(5)

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.7,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.7,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.7,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.9,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.7,Latte

In [5]:
datasets.isnull().sum()

date            0
datetime        0
cash_type       0
card           89
money           0
coffee_name     0
dtype: int64

In [25]:
df=datasets.drop(columns=['datetime'],inplace=True)
df

In [26]:
datasets.shape

(3636, 5)

In [27]:
datasets.head(4)

         date cash_type                 card    coffee_name  new
0  2024-03-01      card  ANON-0000-0000-0001          Latte    0
1  2024-03-01      card  ANON-0000-0000-0002  Hot Chocolate    0
2  2024-03-01      card  ANON-0000-0000-0002  Hot Chocolate    0
3  2024-03-01      card  ANON-0000-0000-0003      Americano    0

In [21]:
from sklearn.preprocessing import LabelEncoder 
le=LabelEncoder()
datasets['new']=le.fit_transform(datasets['cash_type'])
datasets

,date,datetime,cash_type,card,coffee_name,new
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,Latte,0
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,Hot Chocolate,0
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,Hot Chocolate,0
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,Americano,0
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,Latte,0
...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,Cappuccino,0
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,Cocoa,0
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,Cocoa,0
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,Americano,0
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,Latte,0

In [22]:
datasets['cash_type'].unique()

array(['card', 'cash'], dtype=object)

In [23]:
datasets.shape

(3636, 6)

In [24]:
datasets.isnull().sum()

date            0
datetime        0
cash_type       0
card           89
coffee_name     0
new             0
dtype: int64

In [6]:
datasets.fillna(8)

,date,datetime,cash_type,card,money,coffee_name
0,2024-03-01,2024-03-01 10:15:50.520,card,ANON-0000-0000-0001,38.70,Latte
1,2024-03-01,2024-03-01 12:19:22.539,card,ANON-0000-0000-0002,38.70,Hot Chocolate
2,2024-03-01,2024-03-01 12:20:18.089,card,ANON-0000-0000-0002,38.70,Hot Chocolate
3,2024-03-01,2024-03-01 13:46:33.006,card,ANON-0000-0000-0003,28.90,Americano
4,2024-03-01,2024-03-01 13:48:14.626,card,ANON-0000-0000-0004,38.70,Latte
...,...,...,...,...,...,...
3631,2025-03-23,2025-03-23 10:34:54.894,card,ANON-0000-0000-1158,35.76,Cappuccino
3632,2025-03-23,2025-03-23 14:43:37.362,card,ANON-0000-0000-1315,35.76,Cocoa
3633,2025-03-23,2025-03-23 14:44:16.864,card,ANON-0000-0000-1315,35.76,Cocoa
3634,2025-03-23,2025-03-23 15:47:28.723,card,ANON-0000-0000-1316,25.96,Americano
3635,2025-03-23,2025-03-23 18:11:38.635,card,ANON-0000-0000-1275,35.76,Latte