# what is pandas ?
1. Pandas is an open-source Python library that provides high-performance, easy-to-use data structures and data analysis tools, particularly for working with structured data like tabular data, time series, and more. 

2. It is built on top of NumPy and is widely used for data manipulation, cleaning, and analysis in data science and machine learning projects.

***

+ How install pandas librarie

In [1]:
!pip install pandas

Requirement already satisfied: pandas in C:\Users\sangharatna_2022\AppData\Local\Programs\Python\Python312\Lib\site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in C:\Users\sangharatna_2022\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.0.2)
Requirement already satisfied: python-dateutil>=2.8.2 in C:\Users\sangharatna_2022\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in C:\Users\sangharatna_2022\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: tzdata>=2022.7 in C:\Users\sangharatna_2022\AppData\Local\Programs\Python\Python312\Lib\site-packages (from pandas) (2025.1)
Requirement already satisfied: six>=1.5 in C:\Users\sangharatna_2022\AppData\Local\Programs\Python\Python312\Lib\site-packages (from python-dateutil>=2.8.2->pandas) (1.16.0)

In [ ]:
 # import pandas 
import pandas as pd

* what is DataFrame 
1. A DataFrame is a two-dimensional, tabular data structure in the pandas library (Python) that consists of rows and columns, similar to a spreadsheet or SQL table.
2. It allows for easy manipulation, analysis, and storage of structured data with labeled axes.

In [9]:
# using a list
data=pd.DataFrame([20,39,40],columns=['age'])
data

   age
0   20
1   39
2   40

In [8]:
# check version 
pd.__version__

'2.3.3'

In [10]:
# check data type 
print(type(data))

<class 'pandas.core.frame.DataFrame'>

In [11]:
# using dictionry of list 
data_01={
    'name':['Sanghratna','Pranv','Tanu','shradha'],
    'age':[20,21,21,30],
    'Gender':['M','M','F','F']
}

In [12]:
df=pd.DataFrame(data_01)
df

         name  age Gender
0  Sanghratna   20      M
1       Pranv   21      M
2        Tanu   21      F
3     shradha   30      F

* Basic DataFrame understanding

In [ ]:
df.head(4) # top row show

         name  age Gender
0  Sanghratna   20      M
1       Pranv   21      M
2        Tanu   21      F
3     shradha   30      F

In [ ]:
df.tail(2) # bottowm row show

      name  age Gender
2     Tanu   21      F
3  shradha   30      F

In [ ]:
df.sample(2) # ramdom row is show

      name  age Gender
1    Pranv   21      M
3  shradha   30      F

In [ ]:
df.shape # (number of row , number of column) give a tuple

(4, 3)

In [ ]:
df.columns # give a list of all columns name

Index(['name', 'age', 'Gender'], dtype='object')

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 3 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   name    4 non-null      object
 1   age     4 non-null      int64
 2   Gender  4 non-null      object
dtypes: int64(1), object(2)
memory usage: 228.0+ bytes

In [ ]:
df.describe() # give a decriptive information about DataFrame only numerial-value columns

             age
count   4.000000
mean   23.000000
std     4.690416
min    20.000000
25%    20.750000
50%    21.000000
75%    23.250000
max    30.000000

* Save and load csv file

In [ ]:
df.to_csv('practice_DataFrame',index=False) # this file is save --- export datafram

In [31]:
df1=pd.read_csv("train.csv") # file load --- import datafram
df1.head(2)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C

* row and column selection

In [32]:
df[['name']]

         name
0  Sanghratna
1       Pranv
2        Tanu
3     shradha

In [34]:
df[['name','age']]

         name  age
0  Sanghratna   20
1       Pranv   21
2        Tanu   21
3     shradha   30

In [39]:
df.loc[df.name=='Tanu']

   name  age Gender
2  Tanu   21      F

In [41]:
df.loc[(df.name=='Tanu')& (df.age>20)]

   name  age Gender
2  Tanu   21      F

In [ ]:
df.loc[0:4:2] #[start,stop,step] label based

         name  age Gender
0  Sanghratna   20      M
2        Tanu   21      F

In [ ]:
df.iloc[0:4] # index based

         name  age Gender
0  Sanghratna   20      M
1       Pranv   21      M
2        Tanu   21      F
3     shradha   30      F